# Generated by Django 4.2.4 on 2023-09-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product_images')),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('oldamount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
